"""Report generation helpers for validation outputs."""

from __future__ import annotations

from datetime import date
from pathlib import Path

from quadbalance.asset_universe import CASH_SYMBOL, DOMESTIC_STOCK_SYMBOL, GOLD_SYMBOL, QDII_SYMBOL
from quadbalance.instrument_catalog import INSTRUMENT_NAMES
from quadbalance.config import StrategyConfig
from quadbalance.data import PriceMatrixMeta, format_proxy_usage_markdown
from quadbalance.fees import format_fee_assumptions_markdown
from quadbalance.instrument_pool import format_pool_markdown, format_qdii_era_markdown
from quadbalance.profile_thresholds import InvestorProfile, DEFAULT_INVESTOR_PROFILES, overridden_fields
from quadbalance.proxy_sensitivity import SensitivitySummary, format_sensitivity_summary_markdown
from quadbalance.reporting_sections import (
    format_behavior_stress_markdown,
    format_boundary_summary,
    format_cross_border_stress_markdown,
    format_lifecycle_summary,
    format_lock_selection_notes,
    format_long_term_stress_markdown,
    format_path_stress_markdown,
    format_product_risk_markdown,
    format_profile_suitability_summary,
    format_risk_overview_panel,
    format_risk_summary_page,
    format_profile_thresholds_summary,
    format_rebalance_execution_markdown,
    format_risk_map_markdown,
    format_robustness_summary_markdown,
    format_stress_summary_markdown,
    format_uncovered_risk_summary,
)
from quadbalance.simulator import SimulationResult
from quadbalance.reporting_sections import format_s4_path_markdown
from quadbalance.stress import S4PathResult
from quadbalance.validation import ValidationResult

DISCLAIMER = (
    "Historical performance does not guarantee future results. "
    "This document is generated by backtest simulation and is not investment advice."
)


def generate_lock_document(
    config: StrategyConfig,
    sim_result: SimulationResult,
    validation: ValidationResult,
    output_path: Path,
    price_meta: PriceMatrixMeta | None = None,
    sensitivity_summary: SensitivitySummary | None = None,
    s4_path: S4PathResult | None = None,
    investor_profiles: tuple[InvestorProfile, ...] = DEFAULT_INVESTOR_PROFILES,
    intended_profile: str | None = None,
) -> None:
    m = validation.metrics
    stock_weights = config.stock_weights
    lines = [
        "# Strategy Lock Document",
        "",
        f"**Locked date:** {date.today().isoformat()}",
        format_risk_overview_panel(validation),
        format_risk_summary_page(validation),
        f"**Configuration ID:** {config.config_id}",
        f"**Status:** locked",
        "",
        f"**Asset channel:** 场外基金 (off-exchange)",
        "",
        "## Allocation",
        "",
        f"| Quadrant | Weight |",
        f"|----------|--------|",
        f"| Stocks | {config.stocks:.0%} |",
        f"| Bonds | {config.bonds:.0%} |",
        f"| Gold | {config.gold:.0%} |",
        f"| Cash | {config.cash:.0%} |",
        "",
        "## Primary Instruments (场外)",
        "",
        f"- Stocks sub-split: {config.stock_sub_split} "
        f"({stock_weights[DOMESTIC_STOCK_SYMBOL]:.0%} domestic / {stock_weights[QDII_SYMBOL]:.0%} QDII)",
        f"- Stocks: {stock_weights[DOMESTIC_STOCK_SYMBOL]:.0%} {DOMESTIC_STOCK_SYMBOL} {INSTRUMENT_NAMES[DOMESTIC_STOCK_SYMBOL]}, "
        f"{stock_weights[QDII_SYMBOL]:.0%} {QDII_SYMBOL} {INSTRUMENT_NAMES[QDII_SYMBOL]}",
        f"- Bonds: {config.bond_variant} variant",
        f"- Gold: {GOLD_SYMBOL} {INSTRUMENT_NAMES[GOLD_SYMBOL]}",
        f"- Cash: {CASH_SYMBOL} {INSTRUMENT_NAMES[CASH_SYMBOL]}",
        "",
        "## Execution Rules",
        "",
        f"- DCA method: {config.dca_method}",
        f"- Rebalance threshold: ±{config.rebalance_threshold:.0%}",
        f"- QDII daily caps: {config.qdii_daily_caps}",
        "- Sequence-risk profiles: fixed nominal, inflation-adjusted, percentage-of-portfolio, guardrail-based, lumpy expense, and contribution interruption scenarios",
        "",
        "## Backtest Period",
        "",
        f"- Start: {sim_result.effective_start}",
        f"- End: {sim_result.effective_end}",
        "",
        "## Core Metrics",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Annualized return | {m.annualized_return:.2%} |",
        f"| Annualized volatility | {m.annualized_volatility:.2%} |",
        f"| Max drawdown | {m.max_drawdown:.2%} ({m.max_drawdown_peak} → {m.max_drawdown_trough}) |",
        f"| Sharpe ratio | {m.sharpe_ratio:.2f} |",
        f"| Positive years | {m.positive_years_pct:.0%} |",
        f"| Rebalance premium | {m.rebalance_premium:.2%} |",
        f"| Real annualized return | {m.real_annualized_return:.2%} |",
        f"| Real terminal wealth | {m.real_terminal_wealth:.2f}x contributed |",
        f"| Worst rolling 3y real return | {m.worst_rolling_3y_real_return:.2%} |",
        f"| Longest underwater days | {m.longest_underwater_days} |",
        f"| Average drawdown | {m.average_drawdown:.2%} |",
        f"| Ulcer index | {m.ulcer_index:.2%} |",
        f"| Pain index | {m.pain_index:.2%} |",
        f"| CDaR 95 | {m.cdar_95:.2%} |",
        f"| Drawdown events ≤ -10% / -15% / -20% | {m.drawdown_10pct_events} / {m.drawdown_15pct_events} / {m.drawdown_20pct_events} |",
        "",
        format_fee_assumptions_markdown(),
    ]
    if sim_result.qdii_metrics is not None:
        qm = sim_result.qdii_metrics
        lines.extend(["## QDII Execution", "", f"| Metric | Value |", f"|--------|-------|", f"| QDII fill rate | {qm.qdii_fill_rate:.1%} |", f"| Avg pending cash | {qm.avg_pending_cash:,.0f} CNY |", f"| Max pending cash | {qm.max_pending_cash:,.0f} CNY |", f"| Days with pending cash | {qm.pending_cash_days} |", f"| Avg QDII weight gap | {qm.avg_qdii_weight_gap:+.2%} |", ""])
    lines.append(format_qdii_era_markdown())
    rebalance_section = format_rebalance_execution_markdown(sim_result)
    if rebalance_section:
        lines.extend([rebalance_section])
    if price_meta is not None:
        proxy_section = format_proxy_usage_markdown(price_meta)
        if proxy_section:
            lines.extend([proxy_section])
    if sensitivity_summary is not None:
        lines.append(format_sensitivity_summary_markdown(sensitivity_summary))
    if s4_path is not None:
        lines.append(format_s4_path_markdown(s4_path))
    lines.append(format_boundary_summary(validation))
    lines.append(format_lock_selection_notes(intended_profile))
    lines.append(format_profile_suitability_summary(validation))
    lines.append(format_profile_thresholds_summary(investor_profiles, overridden_fields(investor_profiles)))
    lines.append(format_lifecycle_summary(validation.lifecycle_results))
    lines.extend([
        "## Governance Policy",
        "",
        "- Normal: continue scheduled DCA and rebalancing without allocation changes.",
        "- Review-required: perform documented review; do not change target allocation automatically.",
        "- Thesis-broken: freeze optimization-based changes until full re-validation.",
        "- Product replacement may occur within the same quadrant without changing target weights.",
        "- Allocation redesign requires a new validation run and a new strategy lock document.",
        "- Short-term benchmark underperformance alone does not justify redesign.",
        "- Suitability classifications are mechanical screens, not personalized financial advice.",
        "",
    ])
    lines.append(format_stress_summary_markdown(validation.stress_results))
    lines.append(format_path_stress_markdown(getattr(validation, "path_stress_results", [])))
    lines.append(format_behavior_stress_markdown(getattr(validation, "behavior_stress_results", [])))
    lines.append(format_cross_border_stress_markdown(getattr(validation, "cross_border_stress_results", [])))
    lines.append(format_product_risk_markdown(getattr(validation, "product_risk", None)))
    lines.append(format_robustness_summary_markdown(getattr(validation, "robustness", None)))
    lines.append(format_risk_map_markdown(validation))
    lines.append(format_uncovered_risk_summary(validation))
    long_term_results = getattr(validation, "long_term_results", [])
    if long_term_results:
        worst_classification = "thesis-broken" if any(r.classification == "thesis-broken" for r in long_term_results) else (
            "review-required" if any(r.classification == "review-required" for r in long_term_results) else "normal"
        )
        lt3 = next((r for r in long_term_results if r.scenario_id == "LT3"), None)
        lines.extend([
            "## Long-Term Macro Regime Interpretation",
            "",
            "- LT1 is an executable stagflation stress: gold nominal ≈ CPI, cash lags CPI by ~2pp; stocks/long bonds remain weak.",
            "- LT2 emphasizes deflationary stagnation where nominal returns can look acceptable while real growth stays weak.",
            "- LT3 emphasizes a Japan-style balance-sheet recession with prolonged low growth, weaker domestic risk assets, and persistent QDII drag from quota/currency frictions.",
            "- In this framework, overseas assets are not automatically a hedge: they can buffer domestic stagnation, but they can also underperform when currency, quota, and valuation headwinds persist.",
            f"- Overall long-term regime verdict: {worst_classification}.",
        ])
        if lt3 is not None:
            lines.append(
                f"- LT3-specific note: 4% withdrawal {'depletes' if lt3.withdrawal_4pct_depleted else 'does not deplete'} under this synthetic regime; real annualized return {lt3.real_annualized_return:.2%}, 10y real return floor {lt3.worst_rolling_10y_real_return:.2%}."
            )
        lines.append("")
        lines.append(format_long_term_stress_markdown(long_term_results))
    lines.extend(["", format_pool_markdown(), "## Disclaimer", "", DISCLAIMER, ""])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
