"""Acceptance criteria evaluation and strategy lock document."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from pathlib import Path

from quadbalance.benchmarks import BenchmarkResult
from quadbalance.config import (
    CASH_SYMBOL,
    GOLD_SYMBOL,
    INSTRUMENT_NAMES,
    QDII_SYMBOL,
    STOCK_SUB_WEIGHTS,
    StrategyConfig,
)
from quadbalance.instrument_pool import format_pool_markdown
from quadbalance.metrics import PerformanceMetrics
from quadbalance.simulator import SimulationResult
from quadbalance.stress import StressResult

DISCLAIMER = (
    "Historical performance does not guarantee future results. "
    "This document is generated by backtest simulation and is not investment advice."
)


@dataclass
class ValidationResult:
    config_id: str
    passed: bool
    failure_reasons: list[str]
    metrics: PerformanceMetrics
    benchmark_comparison: dict[str, dict[str, float]]
    stress_results: list[StressResult]


def evaluate_acceptance(
    config: StrategyConfig,
    metrics: PerformanceMetrics,
    benchmarks: dict[str, BenchmarkResult],
    stress_results: list[StressResult],
) -> ValidationResult:
    failures: list[str] = []

    if metrics.max_drawdown < -0.25:
        failures.append(f"Criterion 1: max drawdown {metrics.max_drawdown:.1%} > 25%")

    if metrics.worst_year_return < -0.20:
        failures.append(
            f"Criterion 2: worst year {metrics.worst_year_return:.1%} < -20%"
        )

    for sr in stress_results:
        if not sr.passed:
            failures.append(f"Criterion 3: stress {sr.scenario_id} failed")

    cash_bench = benchmarks["cash"]
    if metrics.annualized_return < cash_bench.annualized_return + 0.02:
        failures.append(
            f"Criterion 4: return {metrics.annualized_return:.1%} "
            f"does not exceed cash benchmark by 2%"
        )

    bench_6040 = benchmarks["60_40"]
    return_ok = metrics.annualized_return >= bench_6040.annualized_return - 0.02
    drawdown_ok = metrics.max_drawdown > bench_6040.max_drawdown + 0.05
    if not (return_ok or drawdown_ok):
        failures.append(
            "Criterion 5: neither within 2% of 60/40 return "
            "nor 5% lower max drawdown"
        )

    comp = {
        key: {
            "relative_return": metrics.annualized_return - b.annualized_return,
            "relative_max_drawdown": metrics.max_drawdown - b.max_drawdown,
        }
        for key, b in benchmarks.items()
    }

    return ValidationResult(
        config_id=config.config_id,
        passed=len(failures) == 0,
        failure_reasons=failures,
        metrics=metrics,
        benchmark_comparison=comp,
        stress_results=stress_results,
    )


def generate_lock_document(
    config: StrategyConfig,
    sim_result: SimulationResult,
    validation: ValidationResult,
    output_path: Path,
) -> None:
    m = validation.metrics
    domestic_sym = next(s for s in STOCK_SUB_WEIGHTS if s != QDII_SYMBOL)
    lines = [
        "# Strategy Lock Document",
        "",
        f"**Locked date:** {date.today().isoformat()}",
        f"**Configuration ID:** {config.config_id}",
        f"**Status:** locked",
        "",
        f"**Asset channel:** 场外基金 (off-exchange)",
        "",
        "## Allocation",
        "",
        f"| Quadrant | Weight |",
        f"|----------|--------|",
        f"| Stocks | {config.stocks:.0%} |",
        f"| Bonds | {config.bonds:.0%} |",
        f"| Gold | {config.gold:.0%} |",
        f"| Cash | {config.cash:.0%} |",
        "",
        "## Primary Instruments (场外)",
        "",
        f"- Stocks: {STOCK_SUB_WEIGHTS[domestic_sym]:.0%} {domestic_sym} "
        f"{INSTRUMENT_NAMES[domestic_sym]}, "
        f"{STOCK_SUB_WEIGHTS[QDII_SYMBOL]:.0%} {QDII_SYMBOL} "
        f"{INSTRUMENT_NAMES[QDII_SYMBOL]}",
        f"- Bonds: {config.bond_variant} variant",
        f"- Gold: {GOLD_SYMBOL} {INSTRUMENT_NAMES[GOLD_SYMBOL]}",
        f"- Cash: {CASH_SYMBOL} {INSTRUMENT_NAMES[CASH_SYMBOL]}",
        "",
        "## Execution Rules",
        "",
        f"- DCA method: {config.dca_method}",
        f"- Rebalance threshold: ±{config.rebalance_threshold:.0%}",
        "",
        "## Backtest Period",
        "",
        f"- Start: {sim_result.effective_start}",
        f"- End: {sim_result.effective_end}",
        "",
        "## Core Metrics",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Annualized return | {m.annualized_return:.2%} |",
        f"| Annualized volatility | {m.annualized_volatility:.2%} |",
        f"| Max drawdown | {m.max_drawdown:.2%} ({m.max_drawdown_peak} → {m.max_drawdown_trough}) |",
        f"| Sharpe ratio | {m.sharpe_ratio:.2f} |",
        f"| Positive years | {m.positive_years_pct:.0%} |",
        f"| Rebalance premium | {m.rebalance_premium:.2%} |",
        "",
        "## Stress Test Summary",
        "",
        "| ID | Scenario | Portfolio Return | Passed |",
        "|----|----------|------------------|--------|",
    ]
    for sr in validation.stress_results:
        lines.append(
            f"| {sr.scenario_id} | {sr.scenario_name} | {sr.portfolio_return:.2%} | "
            f"{'✓' if sr.passed else '✗'} |"
        )
    lines.extend(["", format_pool_markdown(), "## Disclaimer", "", DISCLAIMER, ""])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
