"""Acceptance criteria evaluation and strategy lock document."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from pathlib import Path

from quadbalance.benchmarks import BenchmarkResult
from quadbalance.config import (
    CASH_SYMBOL,
    GOLD_SYMBOL,
    INSTRUMENT_NAMES,
    QDII_SYMBOL,
    STOCK_SUB_WEIGHTS,
    StrategyConfig,
)
from quadbalance.data import PriceMatrixMeta, format_proxy_usage_markdown
from quadbalance.fees import format_fee_assumptions_markdown
from quadbalance.instrument_pool import format_pool_markdown, format_qdii_era_markdown
from quadbalance.metrics import PerformanceMetrics
from quadbalance.proxy_sensitivity import SensitivitySummary, format_sensitivity_summary_markdown
from quadbalance.simulator import SimulationResult
from quadbalance.stress import S4PathResult, StressResult, format_s4_path_markdown

DISCLAIMER = (
    "Historical performance does not guarantee future results. "
    "This document is generated by backtest simulation and is not investment advice."
)


@dataclass
class ValidationResult:
    config_id: str
    passed: bool
    failure_reasons: list[str]
    metrics: PerformanceMetrics
    benchmark_comparison: dict[str, dict[str, float]]
    stress_results: list[StressResult]


def evaluate_acceptance(
    config: StrategyConfig,
    metrics: PerformanceMetrics,
    benchmarks: dict[str, BenchmarkResult],
    stress_results: list[StressResult],
) -> ValidationResult:
    failures: list[str] = []

    if metrics.max_drawdown < -0.25:
        failures.append(f"Criterion 1: max drawdown {metrics.max_drawdown:.1%} > 25%")

    if metrics.worst_year_return < -0.20:
        failures.append(
            f"Criterion 2: worst year {metrics.worst_year_return:.1%} < -20%"
        )

    for sr in stress_results:
        if not sr.passed:
            failures.append(f"Criterion 3: stress {sr.scenario_id} failed")

    cash_bench = benchmarks["cash"]
    if metrics.annualized_return < cash_bench.annualized_return + 0.02:
        failures.append(
            f"Criterion 4: return {metrics.annualized_return:.1%} "
            f"does not exceed cash benchmark by 2%"
        )

    bench_6040 = benchmarks["60_40"]
    return_ok = metrics.annualized_return >= bench_6040.annualized_return - 0.02
    drawdown_ok = metrics.max_drawdown > bench_6040.max_drawdown + 0.05
    if not (return_ok or drawdown_ok):
        failures.append(
            "Criterion 5: neither within 2% of 60/40 return "
            "nor 5% lower max drawdown"
        )

    comp = {
        key: {
            "relative_return": metrics.annualized_return - b.annualized_return,
            "relative_max_drawdown": metrics.max_drawdown - b.max_drawdown,
        }
        for key, b in benchmarks.items()
    }

    return ValidationResult(
        config_id=config.config_id,
        passed=len(failures) == 0,
        failure_reasons=failures,
        metrics=metrics,
        benchmark_comparison=comp,
        stress_results=stress_results,
    )


def format_rebalance_execution_markdown(
    sim_result: SimulationResult, config: StrategyConfig
) -> str:
    rm = sim_result.rebalance_metrics
    if rm is None:
        return ""

    lines = [
        "## Rebalance Execution",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Sell shortfall events | {rm.shortfall_event_count} |",
        f"| Total shortfall amount | {rm.total_shortfall_cny:,.0f} CNY |",
        f"| Max single shortfall | {rm.max_single_shortfall_cny:,.0f} CNY |",
        f"| Max post-rebalance deviation | {rm.max_post_rebalance_deviation:.2%} |",
        "",
    ]

    if rm.shortfall_event_count > 0:
        lines.extend(
            [
                "### Sell Shortfall Events",
                "",
                "| Date | Symbol | Requested | Raised | Shortfall |",
                "|------|--------|-----------|--------|-----------|",
            ]
        )
        for event in sim_result.rebalance_shortfalls:
            name = INSTRUMENT_NAMES.get(event.symbol, event.symbol)
            lines.append(
                f"| {event.date} | {event.symbol} {name} | "
                f"{event.requested_cny:,.0f} | {event.raised_cny:,.0f} | "
                f"{event.shortfall_cny:,.0f} |"
            )
        lines.append("")

    if rm.max_post_rebalance_deviation > config.rebalance_threshold:
        lines.append(
            f"*Note: post-rebalance quadrant deviation exceeded threshold "
            f"(±{config.rebalance_threshold:.0%}) in at least one annual rebalance.*"
        )
        lines.append("")

    return "\n".join(lines)


def generate_lock_document(
    config: StrategyConfig,
    sim_result: SimulationResult,
    validation: ValidationResult,
    output_path: Path,
    price_meta: PriceMatrixMeta | None = None,
    sensitivity_summary: SensitivitySummary | None = None,
    s4_path: S4PathResult | None = None,
) -> None:
    m = validation.metrics
    domestic_sym = next(s for s in STOCK_SUB_WEIGHTS if s != QDII_SYMBOL)
    lines = [
        "# Strategy Lock Document",
        "",
        f"**Locked date:** {date.today().isoformat()}",
        f"**Configuration ID:** {config.config_id}",
        f"**Status:** locked",
        "",
        f"**Asset channel:** 场外基金 (off-exchange)",
        "",
        "## Allocation",
        "",
        f"| Quadrant | Weight |",
        f"|----------|--------|",
        f"| Stocks | {config.stocks:.0%} |",
        f"| Bonds | {config.bonds:.0%} |",
        f"| Gold | {config.gold:.0%} |",
        f"| Cash | {config.cash:.0%} |",
        "",
        "## Primary Instruments (场外)",
        "",
        f"- Stocks: {STOCK_SUB_WEIGHTS[domestic_sym]:.0%} {domestic_sym} "
        f"{INSTRUMENT_NAMES[domestic_sym]}, "
        f"{STOCK_SUB_WEIGHTS[QDII_SYMBOL]:.0%} {QDII_SYMBOL} "
        f"{INSTRUMENT_NAMES[QDII_SYMBOL]}",
        f"- Bonds: {config.bond_variant} variant",
        f"- Gold: {GOLD_SYMBOL} {INSTRUMENT_NAMES[GOLD_SYMBOL]}",
        f"- Cash: {CASH_SYMBOL} {INSTRUMENT_NAMES[CASH_SYMBOL]}",
        "",
        "## Execution Rules",
        "",
        f"- DCA method: {config.dca_method}",
        f"- Rebalance threshold: ±{config.rebalance_threshold:.0%}",
        f"- QDII daily caps: {config.qdii_daily_caps}",
        "",
        "## Backtest Period",
        "",
        f"- Start: {sim_result.effective_start}",
        f"- End: {sim_result.effective_end}",
        "",
        "## Core Metrics",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Annualized return | {m.annualized_return:.2%} |",
        f"| Annualized volatility | {m.annualized_volatility:.2%} |",
        f"| Max drawdown | {m.max_drawdown:.2%} ({m.max_drawdown_peak} → {m.max_drawdown_trough}) |",
        f"| Sharpe ratio | {m.sharpe_ratio:.2f} |",
        f"| Positive years | {m.positive_years_pct:.0%} |",
        f"| Rebalance premium | {m.rebalance_premium:.2%} |",
        "",
        format_fee_assumptions_markdown(),
    ]
    if sim_result.qdii_metrics is not None:
        qm = sim_result.qdii_metrics
        lines.extend(
            [
                "## QDII Execution",
                "",
                f"| Metric | Value |",
                f"|--------|-------|",
                f"| QDII fill rate | {qm.qdii_fill_rate:.1%} |",
                f"| Avg pending cash | {qm.avg_pending_cash:,.0f} CNY |",
                f"| Max pending cash | {qm.max_pending_cash:,.0f} CNY |",
                f"| Days with pending cash | {qm.pending_cash_days} |",
                f"| Avg QDII weight gap | {qm.avg_qdii_weight_gap:+.2%} |",
                "",
            ]
        )
        if abs(qm.avg_qdii_weight_gap) > 0.02:
            lines.append(
                f"*Note: average QDII weight deviates from target by "
                f"{qm.avg_qdii_weight_gap:+.2%} of portfolio due to quota limits.*"
            )
            lines.append("")
    lines.append(format_qdii_era_markdown())
    rebalance_section = format_rebalance_execution_markdown(sim_result, config)
    if rebalance_section:
        lines.extend([rebalance_section])
    if price_meta is not None:
        proxy_section = format_proxy_usage_markdown(price_meta)
        if proxy_section:
            lines.extend([proxy_section])
    if sensitivity_summary is not None:
        lines.append(format_sensitivity_summary_markdown(sensitivity_summary))
    if s4_path is not None:
        lines.append(format_s4_path_markdown(s4_path))
    lines.extend(
        [
        "## Stress Test Summary",
        "",
        "| ID | Scenario | Portfolio Return | Passed |",
        "|----|----------|------------------|--------|",
        ]
    )
    for sr in validation.stress_results:
        lines.append(
            f"| {sr.scenario_id} | {sr.scenario_name} | {sr.portfolio_return:.2%} | "
            f"{'✓' if sr.passed else '✗'} |"
        )
    lines.extend(["", format_pool_markdown(), "## Disclaimer", "", DISCLAIMER, ""])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
